### ISSUE TITLE
Scheduler.dll

### ISSUE THREAD

**Issue by beerygaz** [marthoc/docker-homeseer#14]
I'm seeing the following error in my log file when I start the :latest container

Aug-29 11:21:24 AM |   | Error | Compiling script Startup.vb: Visual Basic.Net Compiler version 0.0.0.5943 (Mono 4.7 - tarball) Copyright (C) 2004-2010 Rolf Bjarne Kvinge. All rights reserved. vbnc : Command line : error VBNC2017: The library 'Scheduler.dll' could not be found. There were 1 errors and 0 warnings. Compilation took 00:00:00.3651340
-- | -- | -- | --

I have confirmed that Scheduler.dll is present in the /opt/homeseer directory.

**Comment by E1iTeDa357** [comment]
> I'm seeing the following error in my log file when I start the :latest container
> 
> Aug-29 11:21:24 AM	 	Error	Compiling script Startup.vb: Visual Basic.Net Compiler version 0.0.0.5943 (Mono 4.7 - tarball) Copyright (C) 2004-2010 Rolf Bjarne Kvinge. All rights reserved. vbnc : Command line : error VBNC2017: The library 'Scheduler.dll' could not be found. There were 1 errors and 0 warnings. Compilation took 00:00:00.3651340
> I have confirmed that Scheduler.dll is present in the /opt/homeseer directory.

I ran into the same issue, I have forked Marthoc's version and fixed a bunch of bugs I ran into if you want to give mine a try: https://hub.docker.com/r/e1ite/docker-homeseer
