### ISSUE TITLE
bumping version/image on the hub

### ISSUE THREAD

**Issue by dakipro** [marthoc/docker-homeseer#19]
Hi, thanks for the docker, would do you mind bumping up the version on the docker hub as well, currently latest version is HS3 3.0.0.500.
Thanks again

**Comment by MattL0** [comment]
Does this image contain all the mono packages ?( 6.8 )

**Comment by marthoc** [comment]
New version has been pushed to Docker Hub. 

@MattL0 This image is currently based on mono 5.18.0.225 - which I see is now out of date. I suppose its time to update!
