### ISSUE TITLE
Please add  avahi-daemon to the base container.

### ISSUE THREAD

**Issue by scyto** [marthoc/docker-homeseer#4]
Required for airplay and chromecast plugins.
I can see other plugins wanting zeroconf along the way too.

this is what i did to get it working in a runnig container (i connected using bash process my synology docker UI can spawn)

apt-get install avahi-daemon
service dbus start
service avahi-daemon start

i have no idea what you would change in your startup script (i am really not a linux person - i poke and hope)

**Comment by marthoc** [comment]
I will look into this...

**Comment by marthoc** [comment]
I've just pushed the `avahi` branch to this repo and the `avahi` tag of the image is now building on Docker Hub (i.e. `marthoc/homeseer:avahi`). It's a drop-in replacement for the `latest` tag (meaning you can run it with the same command-line parameters) but runs avahi-daemon and dbus inside the container in addition to HomeSeer. 

Please test and let me know if it's working for you.

**Comment by marthoc** [comment]
As a heads-up, if the image including avahi is working with the plugins that need it, I think I’m going to take your suggested approach and make one image that disables avahi by default but makes it enableable with an environment variable. No real point in having two separate images when including avahi only adds about 30mb.

**Comment by scyto** [comment]
I tested the image last night, yes seems to be good.

Only issue was i normally use the 'clear' option in the synology UI, this recreates containers from original params - only works if the image name hasn't changed between versions.  As such having one image defintely helps people who are less command line inclined. I am happy with whatever call you make, but was pleased with mu results using the env var - i literally had to google every item to figure it out :-)
