### ISSUE TITLE
running mono from root supposedly broke a plugin

### ISSUE THREAD

**Issue by scyto** [marthoc/docker-homeseer#5]
the plugin author said running homeseer from root (i assume he meant mono unpathed but i am not sure) broke his plugin.  While he fixed his plugin (hsbuddy) is there any reason to not call the mono from /usr/bin/mono in the startup script? here is the link, i am not sure if the change is needed given the plugin is now working.

[https://forums.homeseer.com/showpost.php?p=1369688&postcount=309](url)

**Comment by marthoc** [comment]
That link returns 404 for me. In any event, my startup script starts HomeSeer as it's recommended to do with a Linux install, so I'd think that it was the plug-in that was at fault and not the method of starting HS.

Closing this issue.
