### ISSUE TITLE
random startup error about compiling startup.vb and scheduler.dll ?

### ISSUE THREAD

**Issue by scyto** [marthoc/docker-homeseer#7]
I get this randomly, isn't every startup, does it matter?

Jun-12 06:37:51 |   | Error | Compiling script Startup.vb: Visual Basic.Net Compiler version 0.0.0.5943 (Mono 4.6 - tarball) Copyright (C) 2004-2010 Rolf Bjarne Kvinge. All rights reserved. vbnc : Command line : error VBNC2017: The library 'Scheduler.dll' could not be found. There were 1 errors and 0 warnings. Compilation took 00:00:00.3362270
-- | -- | -- | --

**Comment by marthoc** [comment]
I've also seen this message and have investigated it without finding a solution. I've also noticed that it appears randomly. Even though it references Scheduler.dll and so makes you think it's related to Events or timing I never noticed that it affected the way Events worked. I'm going to close this issue but if you ever notice a real impact on running HS that you suspect is down to this Error, please reopen the issue.
